version: "2"
linters:
  enable:
    - bodyclose
    - gocritic
    - gosec
    - misspell
    - nilerr
    - revive
    - unconvert
    - unparam
    - wastedassign
  disable:
    - cyclop
    - exhaustive
    - exhaustruct
    - funlen
    - gocognit
    - nlreturn
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    gocritic:
      disabled-checks:
        - hugeParam
        - rangeValCopy
      enabled-tags:
        - diagnostic
        - performance
    gosec:
      excludes:
        - G104
        - G115
        - G304
    misspell:
      locale: US
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: exported
          arguments:
            - checkPrivateReceivers
        - name: increment-decrement
        - name: indent-error-flow
        - name: range
        - name: receiver-naming
        - name: unexported-return
        - name: var-naming
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gocritic
          - gosec
          - unparam
        path: _test\.go
    paths:
      - dist
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/enterprisedb/icebergexporter
  exclusions:
    generated: lax
    paths:
      - dist
      - third_party$
      - builtin$
      - examples$
