// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"context"
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/metric/embedded"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/enterprisedb/icebergexporter")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/enterprisedb/icebergexporter")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                                        metric.Meter
	mu                                           sync.Mutex
	registrations                                []metric.Registration
	ExporterIcebergBufferFlushDurationSeconds    metric.Float64Histogram
	ExporterIcebergBufferFlushes                 metric.Int64Counter
	ExporterIcebergBufferPendingBytes            metric.Int64ObservableGauge
	ExporterIcebergBufferPendingFiles            metric.Int64ObservableGauge
	ExporterIcebergBufferPendingOldestAgeSeconds metric.Float64ObservableGauge
	ExporterIcebergBufferRows                    metric.Int64ObservableGauge
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// RegisterExporterIcebergBufferPendingBytesCallback sets callback for observable ExporterIcebergBufferPendingBytes metric.
func (builder *TelemetryBuilder) RegisterExporterIcebergBufferPendingBytesCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ExporterIcebergBufferPendingBytes, obs: o})
		return nil
	}, builder.ExporterIcebergBufferPendingBytes)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterExporterIcebergBufferPendingFilesCallback sets callback for observable ExporterIcebergBufferPendingFiles metric.
func (builder *TelemetryBuilder) RegisterExporterIcebergBufferPendingFilesCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ExporterIcebergBufferPendingFiles, obs: o})
		return nil
	}, builder.ExporterIcebergBufferPendingFiles)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterExporterIcebergBufferPendingOldestAgeSecondsCallback sets callback for observable ExporterIcebergBufferPendingOldestAgeSeconds metric.
func (builder *TelemetryBuilder) RegisterExporterIcebergBufferPendingOldestAgeSecondsCallback(cb metric.Float64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerFloat64{inst: builder.ExporterIcebergBufferPendingOldestAgeSeconds, obs: o})
		return nil
	}, builder.ExporterIcebergBufferPendingOldestAgeSeconds)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterExporterIcebergBufferRowsCallback sets callback for observable ExporterIcebergBufferRows metric.
func (builder *TelemetryBuilder) RegisterExporterIcebergBufferRowsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ExporterIcebergBufferRows, obs: o})
		return nil
	}, builder.ExporterIcebergBufferRows)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

type observerInt64 struct {
	embedded.Int64Observer
	inst metric.Int64Observable
	obs  metric.Observer
}

func (oi *observerInt64) Observe(value int64, opts ...metric.ObserveOption) {
	oi.obs.ObserveInt64(oi.inst, value, opts...)
}

type observerFloat64 struct {
	embedded.Float64Observer
	inst metric.Float64Observable
	obs  metric.Observer
}

func (oi *observerFloat64) Observe(value float64, opts ...metric.ObserveOption) {
	oi.obs.ObserveFloat64(oi.inst, value, opts...)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.ExporterIcebergBufferFlushDurationSeconds, err = builder.meter.Float64Histogram(
		"otelcol_exporter_iceberg_buffer_flush_duration_seconds",
		metric.WithDescription("Duration of flush attempts for a table. [Alpha]"),
		metric.WithUnit("s"),
	)
	errs = errors.Join(errs, err)
	builder.ExporterIcebergBufferFlushes, err = builder.meter.Int64Counter(
		"otelcol_exporter_iceberg_buffer_flushes",
		metric.WithDescription("Number of flush attempts for a table. [Alpha]"),
		metric.WithUnit("{flush}"),
	)
	errs = errors.Join(errs, err)
	builder.ExporterIcebergBufferPendingBytes, err = builder.meter.Int64ObservableGauge(
		"otelcol_exporter_iceberg_buffer_pending_bytes",
		metric.WithDescription("Total disk bytes across pending files for a table. Always 0 when the in-memory buffer is in use. [Alpha]"),
		metric.WithUnit("By"),
	)
	errs = errors.Join(errs, err)
	builder.ExporterIcebergBufferPendingFiles, err = builder.meter.Int64ObservableGauge(
		"otelcol_exporter_iceberg_buffer_pending_files",
		metric.WithDescription("Number of disk-backed pending files awaiting flush for a table. Always 0 when the in-memory buffer is in use. [Alpha]"),
		metric.WithUnit("{file}"),
	)
	errs = errors.Join(errs, err)
	builder.ExporterIcebergBufferPendingOldestAgeSeconds, err = builder.meter.Float64ObservableGauge(
		"otelcol_exporter_iceberg_buffer_pending_oldest_age_seconds",
		metric.WithDescription("Age of the oldest pending file for a table, in seconds. Always 0 when no pending files exist or when the in-memory buffer is in use. [Alpha]"),
		metric.WithUnit("s"),
	)
	errs = errors.Join(errs, err)
	builder.ExporterIcebergBufferRows, err = builder.meter.Int64ObservableGauge(
		"otelcol_exporter_iceberg_buffer_rows",
		metric.WithDescription("Current number of buffered rows for a table awaiting flush. [Alpha]"),
		metric.WithUnit("{row}"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
